project_id = "enwjspegjxkqrcmzlzqg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
enable_email_confirmations = false
enable_sms_confirmations = false

[auth.external.google]
# enabled = false
# client_id = ""
# secret = ""

[auth.external.github]
# enabled = false
# client_id = ""
# secret = ""

[edge_functions]
enabled = true
verify_jwt = false

[functions.epo-integration]
verify_jwt = true

[functions.fetch-security-updates]
verify_jwt = false

[functions.list-profiles]
verify_jwt = false

[functions.agent-download-status]
verify_jwt = false

[functions.grant-latest-agent]
verify_jwt = true

[functions.grant-latest-agent-bulk]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.provisioning-orchestrator]
verify_jwt = true

[functions.reconcile-usage]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
